<?php

namespace App\DataProviders;

abstract class CountryDataProvider
{
    public static function data(): array
    {
        return [
            // ["name" => "Afghanistan", "flag" => "🇦🇫"],
            // ["name" => "Albania", "flag" => "🇦🇱"],
            // ["name" => "Algeria", "flag" => "🇩🇿"],
            // ["name" => "Andorra", "flag" => "🇦🇩"],
            // ["name" => "Angola", "flag" => "🇦🇴"],
            // ["name" => "Anguilla", "flag" => "🇦🇮"],
            // ["name" => "Antigua and Barbuda", "flag" => "🇦🇬"],
            // ["name" => "Argentina", "flag" => "🇦🇷"],
            // ["name" => "Armenia", "flag" => "🇦🇲"],
            // ["name" => "Aruba", "flag" => "🇦🇼"],
            // ["name" => "Australia", "flag" => "🇦🇺"],
            // ["name" => "Austria", "flag" => "🇦🇹"],
            // ["name" => "Azerbaijan", "flag" => "🇦🇿"],
            // ["name" => "Bahamas", "flag" => "🇧🇸"],
            // ["name" => "Bahrain", "flag" => "🇧🇭"],
            // ["name" => "Bangladesh", "flag" => "🇧🇩"],
            // ["name" => "Barbados", "flag" => "🇧🇧"],
            // ["name" => "Belarus", "flag" => "🇧🇾"],
            // ["name" => "Belgium", "flag" => "🇧🇪"],
            // ["name" => "Belize", "flag" => "🇧🇿"],
            // ["name" => "Benin", "flag" => "🇧🇯"],
            // ["name" => "Bermuda", "flag" => "🇧🇲"],
            // ["name" => "Bhutan", "flag" => "🇧🇹"],
            // ["name" => "Bolivia", "flag" => "🇧🇴"],
            // ["name" => "Bosnia and Herzegovina", "flag" => "🇧🇦"],
            // ["name" => "Botswana", "flag" => "🇧🇼"],
            // ["name" => "Brazil", "flag" => "🇧🇷"],
            // ["name" => "Brunei Darussalam", "flag" => "🇧🇳"],
            // ["name" => "Bulgaria", "flag" => "🇧🇬"],
            // ["name" => "Burkina Faso", "flag" => "🇧🇫"],
            // ["name" => "Burundi", "flag" => "🇧🇮"],
            // ["name" => "Cambodia", "flag" => "🇰🇭"],
            // ["name" => "Cameroon", "flag" => "🇨🇲"],
            // ["name" => "Canada", "flag" => "🇨🇦"],
            // ["name" => "Cape Verde", "flag" => "🇨🇻"],
            // ["name" => "Cayman Islands", "flag" => "🇰🇾"],
            // ["name" => "Central African Republic", "flag" => "🇨🇫"],
            // ["name" => "Chad", "flag" => "🇹🇩"],
            // ["name" => "Chile", "flag" => "🇨🇱"],
            // ["name" => "China", "flag" => "🇨🇳"],
            // ["name" => "Colombia", "flag" => "🇨🇴"],
            // ["name" => "Comoros", "flag" => "🇰🇲"],
            // ["name" => "Congo", "flag" => "🇨🇬"],
            // ["name" => "Congo (DRC)", "flag" => "🇨🇩"],
            // ["name" => "Cook Islands", "flag" => "🇨🇰"],
            // ["name" => "Costa Rica", "flag" => "🇨🇷"],
            // ["name" => "Croatia", "flag" => "🇭🇷"],
            // ["name" => "Cuba", "flag" => "🇨🇺"],
            // ["name" => "Cyprus", "flag" => "🇨🇾"],
            // ["name" => "Czech Republic", "flag" => "🇨🇿"],
            // ["name" => "Denmark", "flag" => "🇩🇰"],
            // ["name" => "Djibouti", "flag" => "🇩🇯"],
            // ["name" => "Dominica", "flag" => "🇩🇲"],
            // ["name" => "Dominican Republic", "flag" => "🇩🇴"],
            // ["name" => "Ecuador", "flag" => "🇪🇨"],
            // ["name" => "Egypt", "flag" => "🇪🇬"],
            // ["name" => "El Salvador", "flag" => "🇸🇻"],
            // ["name" => "Equatorial Guinea", "flag" => "🇬🇶"],
            // ["name" => "Eritrea", "flag" => "🇪🇷"],
            // ["name" => "Estonia", "flag" => "🇪🇪"],
            // ["name" => "Eswatini", "flag" => "🇸🇿"],
            // ["name" => "Ethiopia", "flag" => "🇪🇹"],
            // ["name" => "Faroe Islands", "flag" => "🇫🇴"],
            // ["name" => "Fiji", "flag" => "🇫🇯"],
            // ["name" => "Finland", "flag" => "🇫🇮"],
            // ["name" => "France", "flag" => "🇫🇷"],
            // ["name" => "French Guiana", "flag" => "🇬🇫"],
            // ["name" => "French Polynesia", "flag" => "🇵🇫"],
            // ["name" => "Gabon", "flag" => "🇬🇦"],
            // ["name" => "Gambia", "flag" => "🇬🇲"],
            // ["name" => "Georgia", "flag" => "🇬🇪"],
            // ["name" => "Germany", "flag" => "🇩🇪"],
            // ["name" => "Ghana", "flag" => "🇬🇭"],
            // ["name" => "Gibraltar", "flag" => "🇬🇮"],
            // ["name" => "Greece", "flag" => "🇬🇷"],
            // ["name" => "grayland", "flag" => "🇬🇱"],
            // ["name" => "Grenada", "flag" => "🇬🇩"],
            // ["name" => "Guadeloupe", "flag" => "🇬🇵"],
            // ["name" => "Guam", "flag" => "🇬🇺"],
            // ["name" => "Guatemala", "flag" => "🇬🇹"],
            // ["name" => "Guinea", "flag" => "🇬🇳"],
            // ["name" => "Guinea-Bissau", "flag" => "🇬🇼"],
            // ["name" => "Guyana", "flag" => "🇬🇾"],
            // ["name" => "Haiti", "flag" => "🇭🇹"],
            // ["name" => "Honduras", "flag" => "🇭🇳"],
            // ["name" => "Hong Kong", "flag" => "🇭🇰"],
            // ["name" => "Hungary", "flag" => "🇭🇺"],
            // ["name" => "Iceland", "flag" => "🇮🇸"],
            // ["name" => "India", "flag" => "🇮🇳"],
            // ["name" => "Indonesia", "flag" => "🇮🇩"],
            // ["name" => "Iran", "flag" => "🇮🇷"],
            // ["name" => "Iraq", "flag" => "🇮🇶"],
            // ["name" => "Ireland", "flag" => "🇮🇪"],
            // ["name" => "Israel", "flag" => "🇮🇱"],
            // ["name" => "Italy", "flag" => "🇮🇹"],
            // ["name" => "Ivory Coast", "flag" => "🇨🇮"],
            // ["name" => "Jamaica", "flag" => "🇯🇲"],
            // ["name" => "Japan", "flag" => "🇯🇵"],
            // ["name" => "Jordan", "flag" => "🇯🇴"],
            // ["name" => "Kazakhstan", "flag" => "🇰🇿"],
            // ["name" => "Kenya", "flag" => "🇰🇪"],
            // ["name" => "Kiribati", "flag" => "🇰🇮"],
            // ["name" => "Kuwait", "flag" => "🇰🇼"],
            // ["name" => "Kyrgyzstan", "flag" => "🇰🇬"],
            // ["name" => "Laos", "flag" => "🇱🇦"],
            // ["name" => "Latvia", "flag" => "🇱🇻"],
            // ["name" => "Lebanon", "flag" => "🇱🇧"],
            // ["name" => "Lesotho", "flag" => "🇱🇸"],
            // ["name" => "Liberia", "flag" => "🇱🇸"],
            // ["name" => "Libya", "flag" => "🇱🇾"],
            // ["name" => "Liechtenstein", "flag" => "🇱🇮"],
            // ["name" => "Lithuania", "flag" => "🇱🇹"],
            // ["name" => "Luxembourg", "flag" => "🇱🇺"],
            // ["name" => "Madagascar", "flag" => "🇲🇬"],
            // ["name" => "Malawi", "flag" => "🇲🇼"],
            // ["name" => "Malaysia", "flag" => "🇲🇾"],
            // ["name" => "Maldives", "flag" => "🇲🇻"],
            // ["name" => "Mali", "flag" => "🇲🇱"],
            // ["name" => "Malta", "flag" => "🇲🇹"],
            // ["name" => "Marshall Islands", "flag" => "🇲🇭"],
            // ["name" => "Mauritania", "flag" => "🇲🇷"],
            // ["name" => "Mauritius", "flag" => "🇲🇺"],
            // ["name" => "Mayotte", "flag" => "🇲🇶"],
            // ["name" => "Mexico", "flag" => "🇲🇽"],
            // ["name" => "Micronesia", "flag" => "🇲🇫"],
            // ["name" => "Moldova", "flag" => "🇲🇩"],
            // ["name" => "Monaco", "flag" => "🇲🇨"],
            // ["name" => "Mongolia", "flag" => "🇲🇳"],
            // ["name" => "Montenegro", "flag" => "🇲🇪"],
            // ["name" => "Morocco", "flag" => "🇲🇦"],
            // ["name" => "Mozambique", "flag" => "🇲🇿"],
            // ["name" => "Myanmar", "flag" => "🇲🇲"],
            // ["name" => "Namibia", "flag" => "🇳🇦"],
            // ["name" => "Nauru", "flag" => "🇳🇷"],
            // ["name" => "Nepal", "flag" => "🇳🇵"],
            // ["name" => "Netherlands", "flag" => "🇳🇱"],
            // ["name" => "New Caledonia", "flag" => "🇳🇨"],
            // ["name" => "New Zealand", "flag" => "🇳🇿"],
            // ["name" => "Nicaragua", "flag" => "🇳🇮"],
            // ["name" => "Niger", "flag" => "🇳🇪"],
            // ["name" => "Nigeria", "flag" => "🇳🇬"],
            // ["name" => "Niue", "flag" => "🇳🇺"],
            // ["name" => "North Macedonia", "flag" => "🇲🇰"],
            // ["name" => "Norfolk Island", "flag" => "🇳🇫"],
            // ["name" => "Northern Mariana Islands", "flag" => "🇲🇵"],
            // ["name" => "Norway", "flag" => "🇳🇴"],
            // ["name" => "Oman", "flag" => "🇴🇲"],
            // ["name" => "Pakistan", "flag" => "🇵🇰"],
            // ["name" => "Palau", "flag" => "🇵🇼"],
            // ["name" => "Palestine", "flag" => "🇵🇸"],
            // ["name" => "Panama", "flag" => "🇵🇦"],
            // ["name" => "Papua New Guinea", "flag" => "🇵🇬"],
            // ["name" => "Paraguay", "flag" => "🇵🇾"],
            // ["name" => "Peru", "flag" => "🇵🇪"],
            // ["name" => "Philippines", "flag" => "🇵🇭"],
            // ["name" => "Pitcairn", "flag" => "🇵🇳"],
            // ["name" => "Poland", "flag" => "🇵🇱"],
            // ["name" => "Portugal", "flag" => "🇵🇹"],
            // ["name" => "Puerto Rico", "flag" => "🇵🇷"],
            // ["name" => "Qatar", "flag" => "🇶🇦"],
            // ["name" => "Romania", "flag" => "🇷🇴"],
            // ["name" => "Russia", "flag" => "🇷🇺"],
            // ["name" => "Rwanda", "flag" => "🇷🇼"],
            // ["name" => "Saint Barthelemy", "flag" => "🇧🇱"],
            // ["name" => "Saint Helena", "flag" => "🇱🇸"],
            // ["name" => "Saint Kitts and Nevis", "flag" => "🇰🇳"],
            // ["name" => "Saint Lucia", "flag" => "🇱🇨"],
            // ["name" => "Saint Martin", "flag" => "🇲🇫"],
            // ["name" => "Saint Pierre and Miquelon", "flag" => "🇵🇲"],
            // ["name" => "Saint Vincent and the Grenadines", "flag" => "🇻🇨"],
            // ["name" => "Samoa", "flag" => "🇼🇸"],
            // ["name" => "San Marino", "flag" => "🇸🇲"],
            // ["name" => "Sao Tome and Principe", "flag" => "🇸🇹"],
            // ["name" => "Saudi Arabia", "flag" => "🇸🇦"],
            // ["name" => "Senegal", "flag" => "🇲🇱"],
            // ["name" => "Serbia", "flag" => "🇷🇸"],
            // ["name" => "Seychelles", "flag" => "🇸🇨"],
            // ["name" => "Sierra Leone", "flag" => "🇸🇱"],
            // ["name" => "Singapore", "flag" => "🇸🇬"],
            // ["name" => "Sint Maarten", "flag" => "🇸🇽"],
            // ["name" => "Slovakia", "flag" => "🇸🇰"],
            // ["name" => "Slovenia", "flag" => "🇸🇮"],
            // ["name" => "Solomon Islands", "flag" => "🇸🇧"],
            // ["name" => "Somalia", "flag" => "🇸🇴"],
            // ["name" => "South Africa", "flag" => "🇿🇦"],
            // ["name" => "South Sudan", "flag" => "🇸🇸"],
            // ["name" => "Spain", "flag" => "🇪🇸"],
            // ["name" => "Sri Lanka", "flag" => "🇱🇰"],
            // ["name" => "Sudan", "flag" => "🇸🇩"],
            // ["name" => "Suriname", "flag" => "🇸🇷"],
            // ["name" => "Svalbard and Jan Mayen", "flag" => "🇸🇯"],
            // ["name" => "Sweden", "flag" => "🇸🇪"],
            // ["name" => "Switzerland", "flag" => "🇨🇭"],
            // ["name" => "Syria", "flag" => "🇸🇾"],
            // ["name" => "Taiwan", "flag" => "🇹🇼"],
            // ["name" => "Tajikistan", "flag" => "🇹🇯"],
            // ["name" => "Tanzania", "flag" => "🇹🇿"],
            // ["name" => "Thailand", "flag" => "🇹🇭"],
            // ["name" => "Timor-Leste", "flag" => "🇹🇱"],
            // ["name" => "Togo", "flag" => "🇹🇬"],
            // ["name" => "Tokelau", "flag" => "🇹🇰"],
            // ["name" => "Tonga", "flag" => "🇹🇴"],
            // ["name" => "Trinidad and Tobago", "flag" => "🇹🇹"],
            // ["name" => "Tunisia", "flag" => "🇹🇳"],
            // ["name" => "Turkey", "flag" => "🇹🇷"],
            // ["name" => "Turkmenistan", "flag" => "🇹🇲"],
            // ["name" => "Tuvalu", "flag" => "🇹🇻"],
            // ["name" => "Uganda", "flag" => "🇺🇬"],
            // ["name" => "Ukraine", "flag" => "🇺🇦"],
            // ["name" => "United Arab Emirates", "flag" => "🇦🇪"],
            // ["name" => "United Kingdom", "flag" => "🇬🇧"],
            // ["name" => "United States", "flag" => "🇺🇸"],
            // ["name" => "Uruguay", "flag" => "🇺🇾"],
            // ["name" => "Uzbekistan", "flag" => "🇺🇿"],
            // ["name" => "Vanuatu", "flag" => "🇻🇺"],
            // ["name" => "Vatican City", "flag" => "🇻🇦"],
            // ["name" => "Venezuela", "flag" => "🇻🇪"],
            // ["name" => "Vietnam", "flag" => "🇻🇳"],
            // ["name" => "Western Sahara", "flag" => "🇪🇭"],
            // ["name" => "Yemen", "flag" => "🇾🇪"],
            // ["name" => "Zambia", "flag" => "🇿🇲"],
            // ["name" => "Zimbabwe", "flag" => "🇿🇼"],

   ["name" => "Afghanistan", "code" => "af", "flag" => "https://flagpedia.net/data/flags/icon/72x54/af.png", "code3" => "AFG"],
    ["name" => "Albania", "code" => "al", "flag" => "https://flagpedia.net/data/flags/icon/72x54/al.png", "code3" => "ALB"],
    ["name" => "Algeria", "code" => "dz", "flag" => "https://flagpedia.net/data/flags/icon/72x54/dz.png", "code3" => "DZA"],
    ["name" => "Andorra", "code" => "ad", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ad.png", "code3" => "AND"],
    ["name" => "Angola", "code" => "ao", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ao.png", "code3" => "AGO"],
    ["name" => "Antigua and Barbuda", "code" => "ag", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ag.png", "code3" => "ATG"],
    ["name" => "Argentina", "code" => "ar", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ar.png", "code3" => "ARG"],
    ["name" => "Armenia", "code" => "am", "flag" => "https://flagpedia.net/data/flags/icon/72x54/am.png", "code3" => "ARM"],
    ["name" => "Australia", "code" => "au", "flag" => "https://flagpedia.net/data/flags/icon/72x54/au.png", "code3" => "AUS"],
    ["name" => "Austria", "code" => "at", "flag" => "https://flagpedia.net/data/flags/icon/72x54/at.png", "code3" => "AUT"],
    ["name" => "Azerbaijan", "code" => "az", "flag" => "https://flagpedia.net/data/flags/icon/72x54/az.png", "code3" => "AZE"],
    ["name" => "Bahamas", "code" => "bs", "flag" => "https://flagpedia.net/data/flags/icon/72x54/bs.png", "code3" => "BHS"],
    ["name" => "Bahrain", "code" => "bh", "flag" => "https://flagpedia.net/data/flags/icon/72x54/bh.png", "code3" => "BHR"],
    ["name" => "Bangladesh", "code" => "bd", "flag" => "https://flagpedia.net/data/flags/icon/72x54/bd.png", "code3" => "BGD"],
    ["name" => "Barbados", "code" => "bb", "flag" => "https://flagpedia.net/data/flags/icon/72x54/bb.png", "code3" => "BRB"],
    ["name" => "Belarus", "code" => "by", "flag" => "https://flagpedia.net/data/flags/icon/72x54/by.png", "code3" => "BLR"],
    ["name" => "Belgium", "code" => "be", "flag" => "https://flagpedia.net/data/flags/icon/72x54/be.png", "code3" => "BEL"],
    ["name" => "Belize", "code" => "bz", "flag" => "https://flagpedia.net/data/flags/icon/72x54/bz.png", "code3" => "BLZ"],
    ["name" => "Benin", "code" => "bj", "flag" => "https://flagpedia.net/data/flags/icon/72x54/bj.png", "code3" => "BEN"],
    ["name" => "Bhutan", "code" => "bt", "flag" => "https://flagpedia.net/data/flags/icon/72x54/bt.png", "code3" => "BTN"],
    ["name" => "Bolivia", "code" => "bo", "flag" => "https://flagpedia.net/data/flags/icon/72x54/bo.png", "code3" => "BOL"],
    ["name" => "Bosnia and Herzegovina", "code" => "ba", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ba.png", "code3" => "BIH"],
    ["name" => "Botswana", "code" => "bw", "flag" => "https://flagpedia.net/data/flags/icon/72x54/bw.png", "code3" => "BWA"],
    ["name" => "Brazil", "code" => "br", "flag" => "https://flagpedia.net/data/flags/icon/72x54/br.png", "code3" => "BRA"],
    ["name" => "Brunei", "code" => "bn", "flag" => "https://flagpedia.net/data/flags/icon/72x54/bn.png", "code3" => "BRN"],
    ["name" => "Bulgaria", "code" => "bg", "flag" => "https://flagpedia.net/data/flags/icon/72x54/bg.png", "code3" => "BGR"],
    ["name" => "Burkina Faso", "code" => "bf", "flag" => "https://flagpedia.net/data/flags/icon/72x54/bf.png", "code3" => "BFA"],
    ["name" => "Burundi", "code" => "bi", "flag" => "https://flagpedia.net/data/flags/icon/72x54/bi.png", "code3" => "BDI"],
    ["name" => "Cabo Verde", "code" => "cv", "flag" => "https://flagpedia.net/data/flags/icon/72x54/cv.png", "code3" => "CPV"],
    ["name" => "Cambodia", "code" => "kh", "flag" => "https://flagpedia.net/data/flags/icon/72x54/kh.png", "code3" => "KHM"],
    ["name" => "Cameroon", "code" => "cm", "flag" => "https://flagpedia.net/data/flags/icon/72x54/cm.png", "code3" => "CMR"],
    ["name" => "Canada", "code" => "ca", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ca.png", "code3" => "CAN"],
    ["name" => "Central African Republic", "code" => "cf", "flag" => "https://flagpedia.net/data/flags/icon/72x54/cf.png", "code3" => "CAF"],
    ["name" => "Chad", "code" => "td", "flag" => "https://flagpedia.net/data/flags/icon/72x54/td.png", "code3" => "TCD"],
    ["name" => "Chile", "code" => "cl", "flag" => "https://flagpedia.net/data/flags/icon/72x54/cl.png", "code3" => "CHL"],
    ["name" => "China", "code" => "cn", "flag" => "https://flagpedia.net/data/flags/icon/72x54/cn.png", "code3" => "CHN"],
    ["name" => "Colombia", "code" => "co", "flag" => "https://flagpedia.net/data/flags/icon/72x54/co.png", "code3" => "COL"],
    ["name" => "Comoros", "code" => "km", "flag" => "https://flagpedia.net/data/flags/icon/72x54/km.png", "code3" => "COM"],
    ["name" => "Congo", "code" => "cg", "flag" => "https://flagpedia.net/data/flags/icon/72x54/cg.png", "code3" => "COG"],
    ["name" => "Costa Rica", "code" => "cr", "flag" => "https://flagpedia.net/data/flags/icon/72x54/cr.png", "code3" => "CRI"],
    ["name" => "Croatia", "code" => "hr", "flag" => "https://flagpedia.net/data/flags/icon/72x54/hr.png", "code3" => "HRV"],
    ["name" => "Cuba", "code" => "cu", "flag" => "https://flagpedia.net/data/flags/icon/72x54/cu.png", "code3" => "CUB"],
    ["name" => "Cyprus", "code" => "cy", "flag" => "https://flagpedia.net/data/flags/icon/72x54/cy.png", "code3" => "CYP"],
    ["name" => "Czech Republic", "code" => "cz", "flag" => "https://flagpedia.net/data/flags/icon/72x54/cz.png", "code3" => "CZE"],
    ["name" => "Denmark", "code" => "dk", "flag" => "https://flagpedia.net/data/flags/icon/72x54/dk.png", "code3" => "DNK"],
    ["name" => "Djibouti", "code" => "dj", "flag" => "https://flagpedia.net/data/flags/icon/72x54/dj.png", "code3" => "DJI"],
    ["name" => "Dominica", "code" => "dm", "flag" => "https://flagpedia.net/data/flags/icon/72x54/dm.png", "code3" => "DMA"],
    ["name" => "Dominican Republic", "code" => "do", "flag" => "https://flagpedia.net/data/flags/icon/72x54/do.png", "code3" => "DOM"],
    ["name" => "Ecuador", "code" => "ec", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ec.png", "code3" => "ECU"],
    ["name" => "Egypt", "code" => "eg", "flag" => "https://flagpedia.net/data/flags/icon/72x54/eg.png", "code3" => "EGY"],
    ["name" => "El Salvador", "code" => "sv", "flag" => "https://flagpedia.net/data/flags/icon/72x54/sv.png", "code3" => "SLV"],
    ["name" => "Equatorial Guinea", "code" => "gq", "flag" => "https://flagpedia.net/data/flags/icon/72x54/gq.png", "code3" => "GNQ"],
    ["name" => "Eritrea", "code" => "er", "flag" => "https://flagpedia.net/data/flags/icon/72x54/er.png", "code3" => "ERI"],
    ["name" => "Estonia", "code" => "ee", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ee.png", "code3" => "EST"],
    ["name" => "Eswatini", "code" => "sz", "flag" => "https://flagpedia.net/data/flags/icon/72x54/sz.png", "code3" => "SWZ"],
    ["name" => "Ethiopia", "code" => "et", "flag" => "https://flagpedia.net/data/flags/icon/72x54/et.png", "code3" => "ETH"],
    ["name" => "Fiji", "code" => "fj", "flag" => "https://flagpedia.net/data/flags/icon/72x54/fj.png", "code3" => "FJI"],
    ["name" => "Finland", "code" => "fi", "flag" => "https://flagpedia.net/data/flags/icon/72x54/fi.png", "code3" => "FIN"],
    ["name" => "France", "code" => "fr", "flag" => "https://flagpedia.net/data/flags/icon/72x54/fr.png", "code3" => "FRA"],
    ["name" => "Gabon", "code" => "ga", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ga.png", "code3" => "GAB"],
    ["name" => "Gambia", "code" => "gm", "flag" => "https://flagpedia.net/data/flags/icon/72x54/gm.png", "code3" => "GMB"],
    ["name" => "Georgia", "code" => "ge", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ge.png", "code3" => "GEO"],
    ["name" => "Germany", "code" => "de", "flag" => "https://flagpedia.net/data/flags/icon/72x54/de.png", "code3" => "DEU"],
    ["name" => "Ghana", "code" => "gh", "flag" => "https://flagpedia.net/data/flags/icon/72x54/gh.png", "code3" => "GHA"],
    ["name" => "Greece", "code" => "gr", "flag" => "https://flagpedia.net/data/flags/icon/72x54/gr.png", "code3" => "GRC"],
    ["name" => "Grenada", "code" => "gd", "flag" => "https://flagpedia.net/data/flags/icon/72x54/gd.png", "code3" => "GRD"],
    ["name" => "Guatemala", "code" => "gt", "flag" => "https://flagpedia.net/data/flags/icon/72x54/gt.png", "code3" => "GTM"],
    ["name" => "Guinea", "code" => "gn", "flag" => "https://flagpedia.net/data/flags/icon/72x54/gn.png", "code3" => "GIN"],
    ["name" => "Guinea-Bissau", "code" => "gw", "flag" => "https://flagpedia.net/data/flags/icon/72x54/gw.png", "code3" => "GNB"],
    ["name" => "Guyana", "code" => "gy", "flag" => "https://flagpedia.net/data/flags/icon/72x54/gy.png", "code3" => "GUY"],
    ["name" => "Haiti", "code" => "ht", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ht.png", "code3" => "HTI"],
    ["name" => "Honduras", "code" => "hn", "flag" => "https://flagpedia.net/data/flags/icon/72x54/hn.png", "code3" => "HND"],
    ["name" => "Hungary", "code" => "hu", "flag" => "https://flagpedia.net/data/flags/icon/72x54/hu.png", "code3" => "HUN"],
    ["name" => "Iceland", "code" => "is", "flag" => "https://flagpedia.net/data/flags/icon/72x54/is.png", "code3" => "ISL"],
    ["name" => "India", "code" => "in", "flag" => "https://flagpedia.net/data/flags/icon/72x54/in.png", "code3" => "IND"],
    ["name" => "Indonesia", "code" => "id", "flag" => "https://flagpedia.net/data/flags/icon/72x54/id.png", "code3" => "IDN"],
    ["name" => "Iran", "code" => "ir", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ir.png", "code3" => "IRN"],
    ["name" => "Iraq", "code" => "iq", "flag" => "https://flagpedia.net/data/flags/icon/72x54/iq.png", "code3" => "IRQ"],
    ["name" => "Ireland", "code" => "ie", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ie.png", "code3" => "IRL"],
    ["name" => "Israel", "code" => "il", "flag" => "https://flagpedia.net/data/flags/icon/72x54/il.png", "code3" => "ISR"],
    ["name" => "Italy", "code" => "it", "flag" => "https://flagpedia.net/data/flags/icon/72x54/it.png", "code3" => "ITA"],
    ["name" => "Jamaica", "code" => "jm", "flag" => "https://flagpedia.net/data/flags/icon/72x54/jm.png", "code3" => "JAM"],
    ["name" => "Japan", "code" => "jp", "flag" => "https://flagpedia.net/data/flags/icon/72x54/jp.png", "code3" => "JPN"],
    ["name" => "Jordan", "code" => "jo", "flag" => "https://flagpedia.net/data/flags/icon/72x54/jo.png", "code3" => "JOR"],
    ["name" => "Kazakhstan", "code" => "kz", "flag" => "https://flagpedia.net/data/flags/icon/72x54/kz.png", "code3" => "KAZ"],
    ["name" => "Kenya", "code" => "ke", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ke.png", "code3" => "KEN"],
    ["name" => "Kiribati", "code" => "ki", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ki.png", "code3" => "KIR"],
    ["name" => "Kuwait", "code" => "kw", "flag" => "https://flagpedia.net/data/flags/icon/72x54/kw.png", "code3" => "KWT"],
    ["name" => "Kyrgyzstan", "code" => "kg", "flag" => "https://flagpedia.net/data/flags/icon/72x54/kg.png", "code3" => "KGZ"],
    ["name" => "Laos", "code" => "la", "flag" => "https://flagpedia.net/data/flags/icon/72x54/la.png", "code3" => "LAO"],
    ["name" => "Latvia", "code" => "lv", "flag" => "https://flagpedia.net/data/flags/icon/72x54/lv.png", "code3" => "LVA"],
    ["name" => "Lebanon", "code" => "lb", "flag" => "https://flagpedia.net/data/flags/icon/72x54/lb.png", "code3" => "LBN"],
    ["name" => "Lesotho", "code" => "ls", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ls.png", "code3" => "LSO"],
    ["name" => "Liberia", "code" => "lr", "flag" => "https://flagpedia.net/data/flags/icon/72x54/lr.png", "code3" => "LBR"],
    ["name" => "Libya", "code" => "ly", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ly.png", "code3" => "LBY"],
    ["name" => "Liechtenstein", "code" => "li", "flag" => "https://flagpedia.net/data/flags/icon/72x54/li.png", "code3" => "LIE"],
    ["name" => "Lithuania", "code" => "lt", "flag" => "https://flagpedia.net/data/flags/icon/72x54/lt.png", "code3" => "LTU"],
    ["name" => "Luxembourg", "code" => "lu", "flag" => "https://flagpedia.net/data/flags/icon/72x54/lu.png", "code3" => "LUX"],
    ["name" => "Madagascar", "code" => "mg", "flag" => "https://flagpedia.net/data/flags/icon/72x54/mg.png", "code3" => "MDG"],
    ["name" => "Malawi", "code" => "mw", "flag" => "https://flagpedia.net/data/flags/icon/72x54/mw.png", "code3" => "MWI"],
    ["name" => "Malaysia", "code" => "my", "flag" => "https://flagpedia.net/data/flags/icon/72x54/my.png", "code3" => "MYS"],
    ["name" => "Maldives", "code" => "mv", "flag" => "https://flagpedia.net/data/flags/icon/72x54/mv.png", "code3" => "MDV"],
    ["name" => "Mali", "code" => "ml", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ml.png", "code3" => "MLI"],
    ["name" => "Malta", "code" => "mt", "flag" => "https://flagpedia.net/data/flags/icon/72x54/mt.png", "code3" => "MLT"],
    ["name" => "Marshall Islands", "code" => "mh", "flag" => "https://flagpedia.net/data/flags/icon/72x54/mh.png", "code3" => "MHL"],
    ["name" => "Mauritania", "code" => "mr", "flag" => "https://flagpedia.net/data/flags/icon/72x54/mr.png", "code3" => "MRT"],
    ["name" => "Mauritius", "code" => "mu", "flag" => "https://flagpedia.net/data/flags/icon/72x54/mu.png", "code3" => "MUS"],
    ["name" => "Mexico", "code" => "mx", "flag" => "https://flagpedia.net/data/flags/icon/72x54/mx.png", "code3" => "MEX"],
    ["name" => "Micronesia", "code" => "fm", "flag" => "https://flagpedia.net/data/flags/icon/72x54/fm.png", "code3" => "FSM"],
    ["name" => "Moldova", "code" => "md", "flag" => "https://flagpedia.net/data/flags/icon/72x54/md.png", "code3" => "MDA"],
    ["name" => "Monaco", "code" => "mc", "flag" => "https://flagpedia.net/data/flags/icon/72x54/mc.png", "code3" => "MCO"],
    ["name" => "Mongolia", "code" => "mn", "flag" => "https://flagpedia.net/data/flags/icon/72x54/mn.png", "code3" => "MNG"],
    ["name" => "Montenegro", "code" => "me", "flag" => "https://flagpedia.net/data/flags/icon/72x54/me.png", "code3" => "MNE"],
    ["name" => "Morocco", "code" => "ma", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ma.png", "code3" => "MAR"],
    ["name" => "Mozambique", "code" => "mz", "flag" => "https://flagpedia.net/data/flags/icon/72x54/mz.png", "code3" => "MOZ"],
    ["name" => "Myanmar", "code" => "mm", "flag" => "https://flagpedia.net/data/flags/icon/72x54/mm.png", "code3" => "MMR"],
    ["name" => "Namibia", "code" => "na", "flag" => "https://flagpedia.net/data/flags/icon/72x54/na.png", "code3" => "NAM"],
    ["name" => "Nauru", "code" => "nr", "flag" => "https://flagpedia.net/data/flags/icon/72x54/nr.png", "code3" => "NRU"],
    ["name" => "Nepal", "code" => "np", "flag" => "https://flagpedia.net/data/flags/icon/72x54/np.png", "code3" => "NPL"],
    ["name" => "Netherlands", "code" => "nl", "flag" => "https://flagpedia.net/data/flags/icon/72x54/nl.png", "code3" => "NLD"],
    ["name" => "New Zealand", "code" => "nz", "flag" => "https://flagpedia.net/data/flags/icon/72x54/nz.png", "code3" => "NZL"],
    ["name" => "Nicaragua", "code" => "ni", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ni.png", "code3" => "NIC"],
    ["name" => "Niger", "code" => "ne", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ne.png", "code3" => "NER"],
    ["name" => "Nigeria", "code" => "ng", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ng.png", "code3" => "NGA"],
    ["name" => "North Macedonia", "code" => "mk", "flag" => "https://flagpedia.net/data/flags/icon/72x54/mk.png", "code3" => "MKD"],
    ["name" => "Norway", "code" => "no", "flag" => "https://flagpedia.net/data/flags/icon/72x54/no.png", "code3" => "NOR"],
    ["name" => "Oman", "code" => "om", "flag" => "https://flagpedia.net/data/flags/icon/72x54/om.png", "code3" => "OMN"],
    ["name" => "Pakistan", "code" => "pk", "flag" => "https://flagpedia.net/data/flags/icon/72x54/pk.png", "code3" => "PAK"],
    ["name" => "Palau", "code" => "pw", "flag" => "https://flagpedia.net/data/flags/icon/72x54/pw.png", "code3" => "PLW"],
    ["name" => "Panama", "code" => "pa", "flag" => "https://flagpedia.net/data/flags/icon/72x54/pa.png", "code3" => "PAN"],
    ["name" => "Papua New Guinea", "code" => "pg", "flag" => "https://flagpedia.net/data/flags/icon/72x54/pg.png", "code3" => "PNG"],
    ["name" => "Paraguay", "code" => "py", "flag" => "https://flagpedia.net/data/flags/icon/72x54/py.png", "code3" => "PRY"],
    ["name" => "Peru", "code" => "pe", "flag" => "https://flagpedia.net/data/flags/icon/72x54/pe.png", "code3" => "PER"],
    ["name" => "Philippines", "code" => "ph", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ph.png", "code3" => "PHL"],
    ["name" => "Poland", "code" => "pl", "flag" => "https://flagpedia.net/data/flags/icon/72x54/pl.png", "code3" => "POL"],
    ["name" => "Portugal", "code" => "pt", "flag" => "https://flagpedia.net/data/flags/icon/72x54/pt.png", "code3" => "PRT"],
    ["name" => "Qatar", "code" => "qa", "flag" => "https://flagpedia.net/data/flags/icon/72x54/qa.png", "code3" => "QAT"],
    ["name" => "Romania", "code" => "ro", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ro.png", "code3" => "ROU"],
    ["name" => "Russia", "code" => "ru", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ru.png", "code3" => "RUS"],
    ["name" => "Rwanda", "code" => "rw", "flag" => "https://flagpedia.net/data/flags/icon/72x54/rw.png", "code3" => "RWA"],
    ["name" => "Saint Kitts and Nevis", "code" => "kn", "flag" => "https://flagpedia.net/data/flags/icon/72x54/kn.png", "code3" => "KNA"],
    ["name" => "Saint Lucia", "code" => "lc", "flag" => "https://flagpedia.net/data/flags/icon/72x54/lc.png", "code3" => "LCA"],
    ["name" => "Saint Vincent and the Grenadines", "code" => "vc", "flag" => "https://flagpedia.net/data/flags/icon/72x54/vc.png", "code3" => "VCT"],
    ["name" => "Samoa", "code" => "ws", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ws.png", "code3" => "WSM"],
    ["name" => "San Marino", "code" => "sm", "flag" => "https://flagpedia.net/data/flags/icon/72x54/sm.png", "code3" => "SMR"],
    ["name" => "Sao Tome and Principe", "code" => "st", "flag" => "https://flagpedia.net/data/flags/icon/72x54/st.png", "code3" => "STP"],
    ["name" => "Saudi Arabia", "code" => "sa", "flag" => "https://flagpedia.net/data/flags/icon/72x54/sa.png", "code3" => "SAU"],
    ["name" => "Senegal", "code" => "sn", "flag" => "https://flagpedia.net/data/flags/icon/72x54/sn.png", "code3" => "SEN"],
    ["name" => "Serbia", "code" => "rs", "flag" => "https://flagpedia.net/data/flags/icon/72x54/rs.png", "code3" => "SRB"],
    ["name" => "Seychelles", "code" => "sc", "flag" => "https://flagpedia.net/data/flags/icon/72x54/sc.png", "code3" => "SYC"],
    ["name" => "Sierra Leone", "code" => "sl", "flag" => "https://flagpedia.net/data/flags/icon/72x54/sl.png", "code3" => "SLE"],
    ["name" => "Singapore", "code" => "sg", "flag" => "https://flagpedia.net/data/flags/icon/72x54/sg.png", "code3" => "SGP"],
    ["name" => "Slovakia", "code" => "sk", "flag" => "https://flagpedia.net/data/flags/icon/72x54/sk.png", "code3" => "SVK"],
    ["name" => "Slovenia", "code" => "si", "flag" => "https://flagpedia.net/data/flags/icon/72x54/si.png", "code3" => "SVN"],
    ["name" => "Solomon Islands", "code" => "sb", "flag" => "https://flagpedia.net/data/flags/icon/72x54/sb.png", "code3" => "SLB"],
    ["name" => "Somalia", "code" => "so", "flag" => "https://flagpedia.net/data/flags/icon/72x54/so.png", "code3" => "SOM"],
    ["name" => "South Africa", "code" => "za", "flag" => "https://flagpedia.net/data/flags/icon/72x54/za.png", "code3" => "ZAF"],
    ["name" => "South Sudan", "code" => "ss", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ss.png", "code3" => "SSD"],
    ["name" => "Spain", "code" => "es", "flag" => "https://flagpedia.net/data/flags/icon/72x54/es.png", "code3" => "ESP"],
    ["name" => "Sri Lanka", "code" => "lk", "flag" => "https://flagpedia.net/data/flags/icon/72x54/lk.png", "code3" => "LKA"],
    ["name" => "Sudan", "code" => "sd", "flag" => "https://flagpedia.net/data/flags/icon/72x54/sd.png", "code3" => "SDN"],
    ["name" => "Suriname", "code" => "sr", "flag" => "https://flagpedia.net/data/flags/icon/72x54/sr.png", "code3" => "SUR"],
    ["name" => "Sweden", "code" => "se", "flag" => "https://flagpedia.net/data/flags/icon/72x54/se.png", "code3" => "SWE"],
    ["name" => "Switzerland", "code" => "ch", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ch.png", "code3" => "CHE"],
    ["name" => "Syria", "code" => "sy", "flag" => "https://flagpedia.net/data/flags/icon/72x54/sy.png", "code3" => "SYR"],
    ["name" => "Taiwan", "code" => "tw", "flag" => "https://flagpedia.net/data/flags/icon/72x54/tw.png", "code3" => "TWN"],
    ["name" => "Tajikistan", "code" => "tj", "flag" => "https://flagpedia.net/data/flags/icon/72x54/tj.png", "code3" => "TJK"],
    ["name" => "Tanzania", "code" => "tz", "flag" => "https://flagpedia.net/data/flags/icon/72x54/tz.png", "code3" => "TZA"],
    ["name" => "Thailand", "code" => "th", "flag" => "https://flagpedia.net/data/flags/icon/72x54/th.png", "code3" => "THA"],
    ["name" => "Timor-Leste", "code" => "tl", "flag" => "https://flagpedia.net/data/flags/icon/72x54/tl.png", "code3" => "TLS"],
    ["name" => "Togo", "code" => "tg", "flag" => "https://flagpedia.net/data/flags/icon/72x54/tg.png", "code3" => "TGO"],
    ["name" => "Tonga", "code" => "to", "flag" => "https://flagpedia.net/data/flags/icon/72x54/to.png", "code3" => "TON"],
    ["name" => "Trinidad and Tobago", "code" => "tt", "flag" => "https://flagpedia.net/data/flags/icon/72x54/tt.png", "code3" => "TTO"],
    ["name" => "Tunisia", "code" => "tn", "flag" => "https://flagpedia.net/data/flags/icon/72x54/tn.png", "code3" => "TUN"],
    ["name" => "Turkey", "code" => "tr", "flag" => "https://flagpedia.net/data/flags/icon/72x54/tr.png", "code3" => "TUR"],
    ["name" => "Turkmenistan", "code" => "tm", "flag" => "https://flagpedia.net/data/flags/icon/72x54/tm.png", "code3" => "TKM"],
    ["name" => "Tuvalu", "code" => "tv", "flag" => "https://flagpedia.net/data/flags/icon/72x54/tv.png", "code3" => "TUV"],
    ["name" => "Uganda", "code" => "ug", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ug.png", "code3" => "UGA"],
    ["name" => "Ukraine", "code" => "ua", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ua.png", "code3" => "UKR"],
    ["name" => "United Arab Emirates", "code" => "ae", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ae.png", "code3" => "ARE"],
    ["name" => "United Kingdom", "code" => "gb", "flag" => "https://flagpedia.net/data/flags/icon/72x54/gb.png", "code3" => "GBR"],
    ["name" => "United States", "code" => "us", "flag" => "https://flagpedia.net/data/flags/icon/72x54/us.png", "code3" => "USA"],
    ["name" => "Uruguay", "code" => "uy", "flag" => "https://flagpedia.net/data/flags/icon/72x54/uy.png", "code3" => "URY"],
    ["name" => "Uzbekistan", "code" => "uz", "flag" => "https://flagpedia.net/data/flags/icon/72x54/uz.png", "code3" => "UZB"],
    ["name" => "Vanuatu", "code" => "vu", "flag" => "https://flagpedia.net/data/flags/icon/72x54/vu.png", "code3" => "VUT"],
    ["name" => "Vatican City", "code" => "va", "flag" => "https://flagpedia.net/data/flags/icon/72x54/va.png", "code3" => "VAT"],
    ["name" => "Venezuela", "code" => "ve", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ve.png", "code3" => "VEN"],
    ["name" => "Vietnam", "code" => "vn", "flag" => "https://flagpedia.net/data/flags/icon/72x54/vn.png", "code3" => "VNM"],
    ["name" => "Yemen", "code" => "ye", "flag" => "https://flagpedia.net/data/flags/icon/72x54/ye.png", "code3" => "YEM"],
    ["name" => "Zambia", "code" => "zm", "flag" => "https://flagpedia.net/data/flags/icon/72x54/zm.png", "code3" => "ZMB"],
    ["name" => "Zimbabwe", "code" => "zw", "flag" => "https://flagpedia.net/data/flags/icon/72x54/zw.png", "code3" => "ZWE"]

        ];
    }
}
